---
abstract: WWW::DanDomain
author:
  - 'Jonas B. Nielsen, <jonasbn@logicLAB.dk>'
build_requires:
  Env: 0
  File::Slurp: 0
  Test::Exception: 0
  Test::MockObject::Extends: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Prereq::Build: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-DanDomain
provides:
  WWW::DanDomain:
    file: lib/WWW/DanDomain.pm
    version: 0.03
requires:
  Carp: 0
  Data::Dumper: 0
  Module::Build: 0.30
  WWW::Mechanize: 0
  WWW::Mechanize::Cached: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-DanDomain
  homepage: http://logicLAB.jira.com/browse/DAND
  license: http://dev.perl.org/licenses/
  repository: http://logicLAB.jira.com/svn/DAND
version: 0.03
