---
name: WWW-DanDomain
version: 0.01
author:
  - 'Jonas B. Nielsen, <jonasbn@logicLAB.dk>'
abstract: WWW::DanDomain
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-DanDomain
  homepage: http://www-dandomain.logicLAB.org
  license: ~
  repository: http://github.com/jonasbn/www-dandomain/tree/master
configure_requires:
  Module::Build: 0
requires:
  Carp: 0
  Data::Dumper: 0
  WWW::Mechanize: 0
build_requires:
  Module::Build: 0
  Test::More: 0
provides:
  WWW::DanDomain:
    file: lib/WWW/DanDomain.pm
    version: 0.01
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
