---
abstract: WWW::DanDomain
author:
  - 'Jonas B. Nielsen, <jonasbn@logicLAB.dk>'
build_requires:
  Env: '0'
  File::Slurp: '0'
  Test::Exception: '0'
  Test::MockObject::Extends: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Prereq::Build: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-DanDomain
provides:
  WWW::DanDomain:
    file: lib/WWW/DanDomain.pm
    version: '0.07'
requires:
  Carp: '0'
  Data::Dumper: '0'
  Module::Build: '0.30'
  Try::Tiny: '0'
  UNIVERSAL::can: '0'
  WWW::Mechanize: '0'
  WWW::Mechanize::Cached: '0'
  perl: '5.008'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-DanDomain
  homepage: http://logicLAB.jira.com/browse/DAND
  license: http://dev.perl.org/licenses/
  projectChangelog: http://logiclab.jira.com/browse/DAND#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  projectSite: http://logicLAB.jira.com/browse/DAND
  projectWiki: http://logiclab.jira.com/wiki/display/DAND/Home
  repository: https://github.com/jonasbn/dand
version: '0.07'
